MvcBootstrap.ExampleApp.Web/ViewModels/EmployeeOption.cs
namespace MvcBootstrap.ExampleApp.Web.ViewModels
{
    using MvcBootstrap.ViewModels;

    public class EmployeeOption : EntityViewModelBase
    {
        public string Name { get; set; }

        public override string ToString()
        {
            return this.Name;
        }
    }
}

MvcBootstrap.ExampleApp.Web/ViewModels/EmployeeViewModel.cs
namespace MvcBootstrap.ExampleApp.Web.ViewModels
{
    using System.ComponentModel.DataAnnotations;

    using MvcBootstrap.ViewModels;
    using MvcBootstrap.ViewModels.Attributes;
    using MvcBootstrap.Web.Mvc.Controllers;

    public class EmployeeViewModel : EntityViewModelBase
    {
        public EmployeeViewModel()
        {
            this.Roles = new Choices<RoleOption>();
            this.Supervisor = new Choice<EmployeeOption>();
        }

        [Required]
        public string Name { get; set; }

        public string Quest { get; set; }

        public Choice<EmployeeOption> Supervisor { get; set; }

        [HideIn(BootstrapActions.List)]
        public Choices<RoleOption> Roles { get; set; }

        public override string ToString()
        {
            return this.Name;
        }
    }
}

MvcBootstrap.ExampleApp.Web/ViewModels/RoleOption.cs
namespace MvcBootstrap.ExampleApp.Web.ViewModels
{
    using MvcBootstrap.ViewModels;

    public class RoleOption : EntityViewModelBase
    {
        public string Title { get; set; }

        public override string ToString()
        {
            return this.Title;
        }
    }
}

MvcBootstrap.ExampleApp.Web/ViewModels/RoleViewModel.cs
namespace MvcBootstrap.ExampleApp.Web.ViewModels
{
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    using MvcBootstrap.ViewModels;
    using MvcBootstrap.ViewModels.Attributes;
    using MvcBootstrap.Web.Mvc.Controllers;

    public class RoleViewModel : EntityViewModelBase
    {
        public RoleViewModel()
        {
            this.Employees = new Choices<EmployeeOption>();
        }

        public string Title { get; set; }

        [HideIn(BootstrapActions.List)]
        public Choices<EmployeeOption> Employees { get; set; }

        public override string ToString()
        {
            return this.Title;
        }
    }
}

MvcBootstrap.ExampleApp.Web/ViewModels/UserProfileViewModel.cs
namespace MvcBootstrap.ExampleApp.Web.ViewModels
{
    using MvcBootstrap.ViewModels.Accounts;

    public class ExampleUserProfileViewModel : UserProfileViewModel
    {
        public string Nickname { get; set; }

        public override string ToString()
        {
            return this.Username;
        }
    }
}

MvcBootstrap.ExampleApp.Web/Controllers/AccountsController.cs
namespace MvcBootstrap.ExampleApp.Web.Controllers
{
    using MvcBootstrap.Data;
    using MvcBootstrap.ExampleApp.Data;
    using MvcBootstrap.ExampleApp.Domain.Models;
    using MvcBootstrap.ExampleApp.Web.ViewModels;
    using MvcBootstrap.Web.Mvc.Controllers;
    using MvcBootstrap.Web.Mvc.Filters;

    [InitializeSimpleMembership(
        typeof(ExampleAppContext), 
        typeof(ExampleUserProfile), 
        ExampleAppContext.ConnectionStringName)]
    public class AccountsController : AccountsControllerBase<ExampleUserProfile, ExampleUserProfileViewModel>
    {
        public AccountsController(IUserProfileRepository<ExampleUserProfile> repository)
            : base(repository)
        {
            //this.Config.RequireAccountConfirmation = true;
        }
    }
}

MvcBootstrap.ExampleApp.Web/Controllers/EmployeesController.cs
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="EmployeesController.cs" company="Carl Gieringer">
//   Carl Gieringer
// </copyright>
// <summary>
//   Defines the EmployeesController type.
// </summary>
// --------------------------------------------------------------------------------------------------------------------

namespace MvcBootstrap.ExampleApp.Web.Controllers
{
    using AutoMapper;

    using MvcBootstrap.ExampleApp.Data.Repositories;
    using MvcBootstrap.ExampleApp.Domain.Models;
    using MvcBootstrap.ExampleApp.Web.ViewModels;
    using MvcBootstrap.Web.Mvc.Controllers;

    /// <summary>
    /// For viewing Employees
    /// </summary>
    public class EmployeesController : BootstrapControllerBase<Employee, EmployeeViewModel>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmployeesController"/> class.
        /// </summary>
        /// <param name="repository">
        /// The repository.
        /// </param>
        /// <param name="rolesRepository">
        /// The roles Repository.
        /// </param>
        public EmployeesController(IEmployeesRepository repository, IRolesRepository rolesRepository)
            : base(repository)
        {
            this.Config.Sort = Sort.By(e => e.Name).ThenBy(e => e.Created);
            this.Config.EntityLabelSelector = e => e.Name;
            this.Config.ViewModelLabelSelector = vm => vm.Name;
            this.Config.Relation(e => e.Roles)
                .HasOptions(e => rolesRepository.GetAll())
                .UsesLabel<RoleOption>(vm => vm.Title);
            this.Config.Relation(e => e.Supervisor)
                .HasOptions(e => repository.GetAll())
                .UsesLabel<EmployeeOption>(vm => vm.Name)
                .CanChooseSelf(false);
        }
    }
}

MvcBootstrap.ExampleApp.Web/Controllers/HomeController.cs
namespace MvcBootstrap.ExampleApp.Web.Controllers
{
    using System.Web.Mvc;

    using MvcBootstrap.Web.Mvc.Controllers;

    public class HomeController : HomeControllerBase
    {
        [AllowAnonymous]
        public override ActionResult Index()
        {
            return this.View();
        }

        [AllowAnonymous]
        public ActionResult About()
        {
            this.ViewBag.Message = "Your app description page.";

            return this.View();
        }

        [AllowAnonymous]
        public ActionResult Contact()
        {
            this.ViewBag.Message = "Your contact page.";

            return this.View();
        }
    }
}

MvcBootstrap.ExampleApp.Web/Controllers/RolesController.cs
namespace MvcBootstrap.ExampleApp.Web.Controllers
{
    using MvcBootstrap.Data;
    using MvcBootstrap.ExampleApp.Data.Repositories;
    using MvcBootstrap.ExampleApp.Domain.Models;
    using MvcBootstrap.ExampleApp.Web.ViewModels;
    using MvcBootstrap.Web.Mvc.Controllers;

    public class RolesController : BootstrapControllerBase<Role, RoleViewModel>
    {
        public RolesController(IRolesRepository repository, IBootstrapRepository<Employee> employeesRepository)
            : base(repository)
        {
            this.Config.Sort = Sort.By(e => e.Title).ThenBy(e => e.Created);
            this.Config.EntityLabelSelector = e => e.Title;
            this.Config.ViewModelLabelSelector = vm => vm.Title;
            this.Config.Relation(e => e.Employees)
                .HasOptions(e => employeesRepository.GetAll())
                .UsesLabel<EmployeeOption>(vm => vm.Name);
            //this.Config.Relation(e => e.ParentRole)
            //    .HasOptions(e => repository.Items)
            //    .UsesLabel<RoleOption>(vm => vm.Title)
            //    .CanChooseSelf(false);
        }
    }
}

MvcBootstrap.ExampleApp.Web/Controllers/UserProfilesController.cs
namespace MvcBootstrap.ExampleApp.Web.Controllers
{
    using MvcBootstrap.Data;
    using MvcBootstrap.ExampleApp.Domain.Models;
    using MvcBootstrap.ExampleApp.Web.ViewModels;
    using MvcBootstrap.Web.Mvc.Controllers;

    public class UserProfilesController : BootstrapControllerBase<ExampleUserProfile, ExampleUserProfileViewModel>
    {
        public UserProfilesController(IBootstrapRepository<ExampleUserProfile> repository)
            : base(repository)
        {
        }
    }
}

MvcBootstrap.ExampleApp.Web/Views/Accounts/ExternalLoginConfirmation.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.ExampleApp.Web.ViewModels
@model MvcBootstrap.ViewModels.Accounts.ExternalLoginRegistrationModel<ExampleUserProfileViewModel>
@{
    ViewBag.PageTitle = "Register";
}

<h1>@ViewBag.PageTitle.</h1>

<h2>Associate your @ViewBag.ProviderDisplayName account.</h2>

@using (this.Bootstrap().BeginForm("ExternalLoginConfirmation", "Accounts", new { ViewBag.ReturnUrl })) 
{
    @Html.AntiForgeryToken()

    @:@this.Bootstrap().ValidationSummary()

    <p>
        You've successfully authenticated with <strong>@ViewBag.ProviderDisplayName</strong>.
        Please enter a user name for this site below and click the Confirm button to finish
        logging in.
    </p>
    
    @:@this.Bootstrap().TextBoxGroupFor(m => m.UserProfileViewModel.Username)
    @:@this.Bootstrap().TextBoxGroupFor(m => m.UserProfileViewModel.Email)
    @:@this.Bootstrap().TextBoxGroupFor(m => m.UserProfileViewModel.Nickname)

    @Html.HiddenFor(m => m.ExternalLoginData)

    @:@this.Bootstrap().SubmitGroup("Register", style: ButtonStyle.Primary)
}

MvcBootstrap.ExampleApp.Web/Views/Accounts/ExternalLoginFailure.cshtml
@{
    ViewBag.PageTitle = "Login Failure";
}

<h1>@ViewBag.PageTitle</h1>
<h2>Your external authentication failed</h2>

MvcBootstrap.ExampleApp.Web/Views/Accounts/Login.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ViewModels.Accounts.LoginModel

@{
    ViewBag.PageTitle = "Log In";
}

<div class="row">
    <div class="span5">
        
        <h2>Login using your account</h2>

        @using (this.Bootstrap().BeginForm(new { ViewBag.ReturnUrl }))
        {
            @Html.AntiForgeryToken()
    
            <text>
                @this.Bootstrap().ValidationSummary()

                @this.Bootstrap().TextBoxGroupFor(m => m.Username)
                @this.Bootstrap().PasswordGroupFor(m => m.Password)
                @this.Bootstrap().CheckboxGroupFor(m => m.RememberMe)
    
                @this.Bootstrap().SubmitGroup("Log In")
            </text>

            <p>
                Or @Html.ActionLink("Register", "Register") if you don't have an account.
            </p>
        }
    </div>
    <div class="span4">
        
        <h2>Use an external service to log in.</h2>

        @Html.Action("ExternalLoginsList", new { ReturnUrl = ViewBag.ReturnUrl })
    </div>
</div>

MvcBootstrap.ExampleApp.Web/Views/Accounts/Manage.cshtml
@model MvcBootstrap.ViewModels.Accounts.LocalPasswordModel
@{
    ViewBag.PageTitle = "Manage Account";
}

<h1>@ViewBag.PageTitle</h1>

<p class="text-success">
    @ViewBag.StatusMessage
</p>

<p>
    You're logged in as <strong>@User.Identity.Name</strong>.
</p>

@if (ViewBag.HasLocalPassword)
{
    @Html.Partial("_ChangePasswordPartial")
}
else
{ 
    @Html.Partial("_SetPasswordPartial")
}

<section id="externalLogins">
    
    @Html.Action("RemoveExternalLogins")

    <h3>Add an external login</h3>

    @Html.Action("ExternalLoginsList", new { ViewBag.ReturnUrl })

</section>

MvcBootstrap.ExampleApp.Web/Views/Accounts/Register.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.ExampleApp.Web.ViewModels
@model MvcBootstrap.ViewModels.Accounts.RegistrationModel<ExampleUserProfileViewModel>
@{
    ViewBag.PageTitle = "Register";
}

<h1>@ViewBag.PageTitle</h1>

@using (this.Bootstrap().BeginForm()) 
{
    @Html.AntiForgeryToken()

    @:@this.Bootstrap().ValidationSummary("There were errors with your registration:")

    @:@this.Bootstrap().TextBoxGroupFor(m => m.UserProfileViewModel.Username)
    @:@this.Bootstrap().TextBoxGroupFor(m => m.UserProfileViewModel.Email)
    @:@this.Bootstrap().TextBoxGroupFor(m => m.UserProfileViewModel.Nickname)
    @:@this.Bootstrap().PasswordGroupFor(m => m.Password)
    @:@this.Bootstrap().PasswordGroupFor(m => m.ConfirmPassword)
        
    @:@this.Bootstrap().SubmitGroup("Register")
}

MvcBootstrap.ExampleApp.Web/Views/Accounts/_ChangePasswordPartial.cshtml
@using MvcBootstrap.Web.Mvc.Views
@model MvcBootstrap.ViewModels.Accounts.LocalPasswordModel

<h3>Change password</h3>

@using (this.Bootstrap().BeginForm("Manage", "Accounts")) 
{
    @Html.AntiForgeryToken()

    @:@this.Bootstrap().ValidationSummary()

    @:@this.Bootstrap().PasswordGroupFor(m => m.OldPassword)
    @:@this.Bootstrap().PasswordGroupFor(m => m.NewPassword)
    @:@this.Bootstrap().PasswordGroupFor(m => m.ConfirmPassword)

    @:@this.Bootstrap().SubmitGroup("Change Password")
}

MvcBootstrap.ExampleApp.Web/Views/Accounts/_ExternalLoginsListPartial.cshtml
@model ICollection<AuthenticationClientData>

@if (Model.Count == 0)
{
    <div class="text-info">
        <p>There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=252166">this article</a>
        for details on setting up this ASP.NET application to support logging in via external services.</p>
    </div>
}
else
{
    using (Html.BeginForm("ExternalLogin", "Accounts", new { ViewBag.ReturnUrl }))
    {
        @Html.AntiForgeryToken()
        <fieldset id="socialLoginList">
            <legend>Log in using another service</legend>
            <p>
                @foreach (AuthenticationClientData p in Model)
                {
                    <button type="submit" 
                            class="btn"
                            name="provider" 
                            value="@p.AuthenticationClient.ProviderName" 
                            title="Log in using your @p.DisplayName account">
                        @p.DisplayName
                    </button>
                }
            </p>
        </fieldset>
    }
}

MvcBootstrap.ExampleApp.Web/Views/Accounts/_RemoveExternalLoginsPartial.cshtml
@using MvcBootstrap.ViewModels.Accounts
@using MvcBootstrap.Web.Mvc.Views
@model ICollection<ExternalLogin>

@if (Model.Count > 0)
{
    <h3>Registered external logins</h3>
    
    <table>
        <tbody>
            @foreach (ExternalLogin externalLogin in Model)
            {
                <tr>
                    <td>
                        @externalLogin.ProviderDisplayName
                    </td>
                    <td>
                        @if (ViewBag.ShowRemoveButton)
                        {
                            using (Html.BeginForm("Disassociate", "Accounts"))
                            {
                                @Html.AntiForgeryToken()
                                <div>
                                    @Html.Hidden("provider", externalLogin.Provider)
                                    @Html.Hidden("providerUserId", externalLogin.ProviderUserId)
                                    @this.Bootstrap().Submit(
                                        "Remove", 
                                        title: string.Format(
                                            "Remove this {0} credential from your account", 
                                            externalLogin.ProviderDisplayName))
                                </div>
                            }
                        }
                        else
                        {
                            @: &nbsp;
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

MvcBootstrap.ExampleApp.Web/Views/Accounts/_SetPasswordPartial.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ViewModels.Accounts.LocalPasswordModel

<p>
    You do not have a local password for this site. Add a local
    password so you can log in without an external login.
</p>

@using (this.Bootstrap().BeginForm("Manage", "Accounts")) 
{
    @Html.AntiForgeryToken()

    @:@this.Bootstrap().ValidationSummary()

    @:@this.Bootstrap().PasswordGroupFor(m => m.NewPassword)
    @:@this.Bootstrap().PasswordGroupFor(m => m.ConfirmPassword)

    @:@this.Bootstrap().SubmitGroup("Set Password")
}

MvcBootstrap.ExampleApp.Web/Views/Employees/Create.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ExampleApp.Web.ViewModels.EmployeeViewModel
@{
    ViewBag.PageTitle = this.PageTitle();
}

@using (this.Bootstrap().BeginCreateForm())
{
    @:@this.Bootstrap().ValidationSummary()
    
    @Html.AntiForgeryToken()

    @Html.EditorForModel("EntityViewModel")
    
    <div class="control-group">
        <div class="controls">
            @this.Bootstrap().Submit("Create", Icon.Ok, ButtonStyle.Primary)
            @this.Bootstrap().CancelLink()
        </div>
    </div>
}

@section scripts
{
    <script>
        jQuery(function($) {
            $('select.related-entity').chosen({
                allow_single_deselect: true
            });
        })
    </script>
}

MvcBootstrap.ExampleApp.Web/Views/Employees/Delete.cshtml
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ExampleApp.Web.ViewModels.EmployeeViewModel
@{
    ViewBag.Title = this.EntityActionTitle();
}

@this.Bootstrap().ReturnLink()

<h1>@ViewBag.Title</h1>

@if (this.ViewData.ModelState.IsValid)
{
    <p>
        Are you sure you want to delete @this.Bootstrap().ViewModelLabelForModel()?
    </p>
}

@this.Bootstrap().ValidationSummary()

@using (this.Bootstrap().BeginUpdateForm())
{
    @Html.AntiForgeryToken()
    
    <text>
        @this.Bootstrap().Submit("Delete", new { @class = "btn btn-danger" })
        @this.Bootstrap().CancelLink(Model.Id)
    </text>
}

MvcBootstrap.ExampleApp.Web/Views/Employees/List.cshtml
@using MvcBootstrap.ExampleApp.Web.ViewModels
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model IList<EmployeeViewModel>
@{
    ViewBag.PageTitle = this.ControllerName();
}

@Html.DisplayForModel("EntityTable")

@this.Bootstrap().CreateLink()

MvcBootstrap.ExampleApp.Web/Views/Employees/Read.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ExampleApp.Web.ViewModels.EmployeeViewModel
@{
    ViewBag.PageTitle = this.PageTitle();
    int id = Model.Id.Value;
}

<div class="form-horizontal">
    @Html.DisplayForModel("EntityViewModel")

    <div class="control-group">
        <div class="controls">
            <div class="btn-group">
                
                @this.Bootstrap().UpdateLink(id)
                
                <button class="btn dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        @this.Bootstrap().DeleteLink(id, style:ButtonStyle.None)
                    </li>
                </ul>

            </div>
        </div>
    </div>
</div>

MvcBootstrap.ExampleApp.Web/Views/Employees/Update.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ExampleApp.Web.ViewModels.EmployeeViewModel
@{
    ViewBag.PageTitle = this.PageTitle();
}

@this.Bootstrap().ValidationSummary()

@using (this.Bootstrap().BeginUpdateForm())
{
    @Html.AntiForgeryToken()

    @Html.EditorForModel("EntityViewModel")
    
    <div class="control-group">
        <div class="controls">
            @this.Bootstrap().Submit("Save", Icon.Ok, ButtonStyle.Primary)
            @this.Bootstrap().CancelLink(Model.Id)
        </div>
    </div>
}

@section scripts
{
    <script>
        jQuery(function($) {
            $('select.related-entity').chosen({
                allow_single_deselect: true
            });
        })
    </script>
}

MvcBootstrap.ExampleApp.Web/Views/Home/About.cshtml
@{
    ViewBag.PageTitle = "About";
}

<hgroup class="title">
    <h1>@ViewBag.PageTitle.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

MvcBootstrap.ExampleApp.Web/Views/Home/Contact.cshtml
@{
    ViewBag.PageTitle = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.PageTitle.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

MvcBootstrap.ExampleApp.Web/Views/Home/Index.cshtml
@{
    ViewBag.PageTitle = "Home Page";
}

<ul>
    <li>
        @Html.ActionLink("Employees", "List", "Employees")
    </li>
    <li>
        @Html.ActionLink("Roles", "List", "Roles")
    </li>
    <li>
        @Html.ActionLink("User Profiles", "List", "UserProfiles")
    </li>
</ul>

MvcBootstrap.ExampleApp.Web/Views/Roles/Create.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ExampleApp.Web.ViewModels.RoleViewModel
@{
    ViewBag.PageTitle = this.PageTitle();
}


@using (this.Bootstrap().BeginCreateForm())
{
    @Html.AntiForgeryToken()

    @:@this.Bootstrap().ValidationSummary()

    @Html.EditorForModel("EntityViewModel")
    
    <div class="control-group">
        <div class="controls">
            @this.Bootstrap().Submit("Save", Icon.Plus, ButtonStyle.Primary)
            @this.Bootstrap().CancelLink()
        </div>
    </div>
}

@section scripts
{
    <script>
        jQuery(function($) {
            $('select.related-entity').chosen({
                allow_single_deselect: true
            });
        })
    </script>
}

MvcBootstrap.ExampleApp.Web/Views/Roles/Delete.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ExampleApp.Web.ViewModels.RoleViewModel
@{
    ViewBag.PageTitle = this.PageTitle();
}

@if (this.ViewData.ModelState.IsValid)
{
    <p>
        Are you sure you want to delete @this.Bootstrap().ViewModelLabelForModel()?
    </p>
}


@using (this.Bootstrap().BeginUpdateForm())
{
    @Html.AntiForgeryToken()
    
    @:@this.Bootstrap().ValidationSummary()

    @:@this.Bootstrap().Submit("Delete", Icon.Ok, ButtonStyle.Danger)
    @:@this.Bootstrap().CancelLink(Model.Id)
}

MvcBootstrap.ExampleApp.Web/Views/Roles/List.cshtml
@using MvcBootstrap.ExampleApp.Web.ViewModels
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model IList<RoleViewModel>
@{
    ViewBag.PageTitle = this.ControllerName();
}

@Html.DisplayForModel("EntityTable")

@this.Bootstrap().CreateLink()

MvcBootstrap.ExampleApp.Web/Views/Roles/Read.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ExampleApp.Web.ViewModels.RoleViewModel
@{
    ViewBag.PageTitle = this.PageTitle();
    int id = Model.Id.Value;
}

<div class="form-horizontal">
    @Html.DisplayForModel("EntityViewModel")

    <div class="control-group">
        <div class="controls">
            <div class="btn-group">
                @this.Bootstrap().UpdateLink(id)
                <button class="btn dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li>
                        @this.Bootstrap().DeleteLink(id, style:ButtonStyle.None)
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

MvcBootstrap.ExampleApp.Web/Views/Roles/Update.cshtml
@using MvcBootstrap.Web.Mvc.Views
@using MvcBootstrap.Web.Mvc.Views.Extensions
@model MvcBootstrap.ExampleApp.Web.ViewModels.RoleViewModel
@{
    ViewBag.PageTitle = this.PageTitle();
}


@using (this.Bootstrap().BeginUpdateForm())
{
    @Html.AntiForgeryToken()

    @:@this.Bootstrap().ValidationSummary()

    @Html.EditorForModel("EntityViewModel")
    
    <div class="control-group">
        <div class="controls">
            @this.Bootstrap().Submit("Save", Icon.Ok, ButtonStyle.Primary)
            @this.Bootstrap().CancelLink(Model.Id)
        </div>
    </div>
}

@section scripts
{
    <script>
        jQuery(function ($) {
            $('select.related-entity').chosen({
                allow_single_deselect: true
            });
        })
    </script>
}

MvcBootstrap.ExampleApp.Web/Views/Shared/FlashMessage.cshtml
@model MvcBootstrap.Web.Mvc.Controllers.FlashMessage

<div class="alert @Html.AttributeEncode(Model.CssClass())">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    @Model.Message
</div>